version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      # Dies ist notwendig, um auf den Docker Daemon zuzugreifen und Container zu steuern
      - /var/run/docker.sock:/var/run/docker.sock
      
    # Metrik-Ports sind entfernt
    # ports:
    #   - "8080:8080" 
      
    # Das fehlerverursachende --metrics-addr ist entfernt
    command: --cleanup